services:
  stt_server:
    profiles:
      - default
      - full
    restart: unless-stopped  
    image: stt_server:1.0
    container_name: stt_server
    hostname: stt_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    logging:
      options:
        max-size: "10m"
        max-file: "3"    
    networks:
      logus2k_network:
    ports:
      - "2700:2700"
    volumes:
      - ~/env/assets/stt_server/data:/stt_server/data:ro

networks:
  logus2k_network:
    external: true
